name: composite step
description: A composite step
inputs:
  variable:
    description: "A variable input"
    required: false
    default: "cool default bro"
outputs:
  out:
    description: "A variable input"
    value: ${{ steps.out.outputs.out }}
runs:
  using: composite
  steps:
    - name: Run
      id: out
      shell: bash
      run: |
        echo "I run with ${{ inputs.var }}"
        echo "out=123" >> $GITHUB_OUTPUT
