name: conditional step
inputs:
  condition:
    description: "The condition"
    required: true
  manual:
    description: "A manual override"
    default: ''
    required: false
  runit:
    description: "Just runit"
    default: ''
    required: false
# An implicit input is the environment variable `build_dir`.
runs:
  using: composite
  steps:
    - name: runit
      shell: bash
      if: inputs.runit == 'yes'
      run: |
        echo "We ran it!!!"

    - name: OR confidtion
      shell: bash
      if: env.CONAN_LOGIN_USERNAME_RIPPLE != '' || env.CONAN_PASSWORD_RIPPLE != ''
      run: |
        echo "Well neither both must have been defined..."
        echo "CONAN_LOGIN_USERNAME_RIPPLE: $CONAN_LOGIN_USERNAME_RIPPLE"
        echo "CONAN_PASSWORD_RIPPLE: $CONAN_PASSWORD_RIPPLE"
    - name: AND confidtion
      shell: bash
      if: env.CONAN_LOGIN_USERNAME_RIPPLE != '' && env.CONAN_PASSWORD_RIPPLE != ''
      run: |
        echo "Well they must have BOTH been defined..."
        echo "CONAN_LOGIN_USERNAME_RIPPLE: $CONAN_LOGIN_USERNAME_RIPPLE"
        echo "CONAN_PASSWORD_RIPPLE: $CONAN_PASSWORD_RIPPLE"

    - name: step 1
      if: env.OVERRIDE != ''
      shell: bash
      run: |
        echo "This can be overridden if OVERRIDE != '' in the env"

    - name: step 2
      if: env.OVERRIDE == ''
      shell: bash
      run: |
        echo "OVERRIDE was == '' !"

    - name: step 3
      if: inputs.manual == ''
      shell: bash
      run: |
        echo "The default for OVERRIDE"

    - name: step 4
      if: inputs.manual != ''
      shell: bash
      run: |
        echo "manual must have been anything other than '' in the input"
