name: conditional step
inputs:
  condition:
    description: "The condition"
    required: true
  manual:
    description: "A manual override"
    default: ''
    required: false
  runit:
    description: "Just runit"
    default: ''
    required: false
# An implicit input is the environment variable `build_dir`.
runs:
  using: composite
  steps:
    - name: AND run
      if: env.CONAN_LOGIN_USERNAME_RIPPLE != '' && env.CONAN_PASSWORD_RIPPLE != ''
      shell: bash
      run: |
        echo "BOTH were not empty!"
        echo it was: ${{ inputs.runit }}

    - name: OR run
      if: env.CONAN_LOGIN_USERNAME_RIPPLE != '' || env.CONAN_PASSWORD_RIPPLE != ''
      shell: bash
      run: |
        echo "We ran it!!!because either was not empty!"
        echo it was: ${{ inputs.runit }}

    - name: sanity check
      shell: bash
      run: |
        echo "env.CONAN_LOGIN_USERNAME_RIPPLE: ${{ env.CONAN_LOGIN_USERNAME_RIPPLE }}"
        echo "CONAN_LOGIN_USERNAME_RIPPLE: ${CONAN_LOGIN_USERNAME_RIPPLE}"
