on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
      os:
        required: true
        type: string

    secrets:
      SECRET_2:
        required: true

jobs:
  reusable_workflow_job:
    permissions:
      contents: read
      pull-requests: write
    name: "${{ inputs.os }} run"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/labeler@v5
      with:
        configuration-path: ${{ inputs.config-path }}
        # repo-token: ${{ secrets.SECRET_2 }}
    - name: Os message
      run: echo "I should run on ${{ inputs.os }}"
      # run: echo "I should run on a specific os"
