on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
      os:
        required: true
        type: string

    secrets:
      personal_access_token:
        required: true

jobs:
  reusable_workflow_job:
    name: "${{ inputs.os }} run"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
      with:
        repo-token: ${{ secrets.personal_access_token }}
        configuration-path: ${{ inputs.config-path }}
    - name: Os message
      run: echo "I should run on ${{ inputs.os }}"
      # run: echo "I should run on a specific os"
