name: Build Linux (Container)
description: "Build on Linux"

on:
  workflow_call:
    inputs:
      profile:
        required: true
        type: string
        default: "default"
      container:
        required: false
        type: string
        default: "ghcr.io/xrplf/rippled-build-ubuntu:aaf5e3e"
      python:
        type: string
        default: "3.11"


jobs:
  build:
    # runs-on: [self-hosted, heavy]
    runs-on: "ubuntu-latest"
    container:
      image: ${{ inputs.container }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python (for Conan)
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python}}

      - name: Cache Conan packages
        uses: actions/cache@v3
        with:
          path: ~/.conan/data
          key: ${{ runner.os }}-conan-${{ hashFiles('conanfile.txt') }}
          restore-keys: |
            ${{ runner.os }}-conan-

      - name: Install Conan
        run: pip install conan

      - name: Conan Install dependencies
        uses: ./.github/actions/conan-install
        env:
          CONAN_URL: http://18.143.149.228:8081/artifactory/api/conan/dev
        with:
            configuration: ${{ env.configuration }}
            profile: ${{ env.profile }}

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build
