name: Trigger

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build-package:
    runs-on: ubuntu-latest
    container: ghcr.io/astral-sh/uv:python3.13-bookworm-slim
    steps:
      - name: update
        run: |
          apt-get update && apt-get install gpg -y
