name: Build (macOS / Windows)

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      profile:
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ inputs.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python (for Conan)
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Cache Conan packages
        uses: actions/cache@v3
        with:
          path: ~/.conan/data
          key: ${{ runner.os }}-conan-${{ hashFiles('conanfile.txt') }}
          restore-keys: |
            ${{ runner.os }}-conan-

      - name: Install Conan
        run: pip install conan

      - name: Conan Install
        run: conan install . --profile ${{ inputs.profile }} --build=missing

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build
