name: Reusable build

on:
  workflow_call:
    inputs:
      runs_on:
        description: Runner to run the job on
        required: true
        type: string

      branch:
        description: "The container object as a JSON string (leave empty to run natively)"
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: ${{ inputs.runs_on }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # We need to fetch tags to have correct version in the release
          # The workaround is based on https://github.com/actions/checkout/issues/1467
          fetch-tags: true
          ref: ${{ inputs.branch }}


      - name: Check branch
        run: |
            echo "cools its"
            cat file.txt
