name: Conditionally Run Step

on: workflow_dispatch

jobs:
  secret_test:
    env:
        my_secret: ${{ secrets.MY_SECRET }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: bracket_string
        if: ${{ env.my_secret != '' }}
        run: |
            set -ex
            echo "The variable MY_SECRET is defined as ${{ env.my_secret }}"
            echo "The variable MY_VAR is defined as ${{ env.my_var }}"

      # - name: no_bracket_string
      #   if: env.my_secret != ''
      #   run: |
      #       set -ex
      #       echo "The variable MY_SECRET is defined as ${{ env.my_secret }}"
      #       echo "The variable MY_VAR is defined as ${{ env.my_var }}"

      # - name: bracket_null
      #   if: ${{ env.my_secret != null }}
      #   run: |
      #       set -ex
      #       echo "The variable MY_SECRET is defined as ${{ env.my_secret }}"
      #       echo "The variable MY_VAR is defined as ${{ env.my_var }}"

      # - name: no_bracket_null
      #   if: env.my_secret != null
      #   run: |
      #       echo "The variable MY_SECRET is defined as ${{ env.my_secret }}"
      #       echo "The variable MY_VAR is defined as ${{ env.my_var }}"

  # null_secret_test:
  #   env:
  #       my_null_secret: ${{ secrets.MY_NULL_SECRET }}
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: bracket_string
  #       if: ${{ env.my_null_secret != '' }}
  #       run: echo "The secret MY_NULL_SECRET is defined."

  #     - name: no_bracket_string
  #       if: env.my_null_secret != ''
  #       run: echo "The secret MY_NULL_SECRET is defined."

  #     - name: bracket_null
  #       if: ${{ env.my_null_secret != null }}
  #       run: echo "The secret MY_NULL_SECRET is defined."

  #     - name: no_bracket_null
  #       if: env.my_null_secret != null
  #       run: echo "The secret MY_NULL_SECRET is defined."
