name: Test ma_build

on:
  push:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        description: branch to build
        default: main

jobs:
  test_ma_build:
    uses: ./.github/workflows/ma_build_rw.yml
    with:
      runs_on: ubuntu-latest
      branch: ${{ inputs.branch }}
