name: Reusable image build

on:
  workflow_call:
    inputs:
      runs_on:
        description: Runner to run the job on
        required: true
        type: string

      branch:
        description: "The branch to build"
        required: true
        type: string

jobs:
  build:
    uses: ./.github/workflows/build_me.yml
    with:
      runs_on: ${{ inputs.runs_on }}
      branch: ${{ inputs.branch }}
