on: [push]

jobs:
  build:
    name: ${{ matrix.platform }}-${{ matrix.compiler }}-${{ matrix.configuration }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux
        compiler:
          - gcc
          - clang
        configuration:
          - Debug
          - Release

    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
      - uses: actions/checkout@v4
      - run: echo "cool"
