name: Test tings
env:
  DEFAULT_WORKLOAD_COMMIT: main
  NUM_VALIDATORS: 5
  CONAN_LOGIN_USERNAME_RIPPLE: ${{ vars.CONAN_LOGIN_USERNAME_RIPPLE }}
  CONAN_PASSWORD_RIPPLE: ${{ vars.CONAN_PASSWORD_RIPPLE }}
on:
  push:
  workflow_dispatch:
    inputs:
      rippled_repo:
        description: 'Git rippled repo'
        default: https://github.com/XRPLF/rippled.git
        required: true
        type: string
      rippled_commit:
        description: 'Git rippled branch/commit'
        default: develop
        required: true
        type: string
      environment:
        type: environment
        description: Select the environment
      boolean:
        type: boolean
        description: True or False
        default: True
      choice:
        type: choice
        description: Make a choice
        options:
        - foo
        - bar
        - baz
      workload_commit:
        description: 'Git workload branch/commit'
        default: main
        required: true
        type: string

jobs:
  build_1:
    name: "Boolean is ${{ inputs.boolean }} or ${{ github.event.inputs.boolean  }}"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: "Inputs: ${{ inputs.boolean }} or ${{ github.event.inputs.boolean  }}"

        run: |
          echo "environment is ${{ github.event.inputs.environment }} / ${{ inputs.environment }}"
          echo "boolean is ${{ github.event.inputs.boolean }}" / ${{ inputs.boolean }}
          echo "choice is ${{ github.event.inputs.choice }}" / ${{ inputs.choice }}

      - name: Check env in workflow
        run: |
          echo "env.CONAN_LOGIN_USERNAME_RIPPLE: ${{ env.CONAN_LOGIN_USERNAME_RIPPLE }}"
          echo "CONAN_LOGIN_USERNAME_RIPPLE: ${CONAN_LOGIN_USERNAME_RIPPLE}"
      - name: use action
        uses: ./.github/actions/cond
