name: Test cache

on:
  push:
  workflow_dispatch:
    inputs:
      rippled_repo:
        description: 'Git rippled repo'
        default: https://github.com/XRPLF/rippled.git
        required: true
        type: string
      rippled_commit:
        description: 'Git rippled branch/commit'
        default: develop
        required: true
        type: string

env:
  DEFAULT_COMMIT: develop
  DEFAULT_REPO: "https://github.com/XRPLF/rippled.git"

jobs:
  build_deps:
    runs-on: ubuntu-latest
    # container: ghcr.io/xrplf/ci/debian-bookworm:clang-16
    # container: ghcr.io/xrplf/ci/ubuntu-jammy:gcc-12r) ||
    steps:
      - uses: actions/checkout@v1

      - name: get rippled commit id
        id: rippled_commit_id
        env:
          COMMIT: "${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.rippled_commit) || env.DEFAULT_COMMIT }}"
          REPO: "${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.rippled_repo) || env.DEFAULT_REPO }}"

        run: |
          echo "rippled_commit_id=$(git ls-remote --heads $REPO $COMMIT | cut -f 1)" >> $GITHUB_OUTPUT

      - name: use built image
        id: rippled_image_cache
        uses: actions/cache@v4
        with:
          path: image_dir
          key: rippled-${{ steps.rippled_commit_id.outputs.rippled_commit_id }}

      - name: build rippled
        if: steps.rippled_image_cache.outputs.cache-hit != 'true'
        env:
          COMMIT: "${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.rippled_commit) || env.DEFAULT_COMMIT }}"
        run: |
          set -x
          echo "trying again"
          echo "Hopefully _not_ building image"
          image="${{ steps.rippled_commit_id.outputs.rippled_commit_id }}-image"
          image_dir="image_dir"
          touch $image
          echo "Created $image"
          mkdir $image_dir && mv $image $image_dir
          ls -l $image_dir
