name: Test tings
env:
  DEFAULT_WORKLOAD_COMMIT: main
  NUM_VALIDATORS: 5

on:
  push:
  workflow_dispatch:
    inputs:
      rippled_repo:
        description: 'Git rippled repo'
        default: https://github.com/XRPLF/rippled.git
        required: true
        type: string
      rippled_commit:
        description: 'Git rippled branch/commit'
        default: develop
        required: true
        type: string
      environment:
        type: environment
        description: Select the environment
      boolean:
        type: boolean
        description: True or False
        default: True
      choice:
        type: choice
        description: Make a choice
        options:
        - foo
        - bar
        - baz
      workload_commit:
        description: 'Git workload branch/commit'
        default: main
        required: true
        type: string

jobs:
  build_deps:
    runs-on: ubuntu-latest
    container: ghcr.io/xrplf/ci/debian-bookworm:clang-16
    steps:
      - name: generate dependencies
        id: deps
        run: |
          echo $PWD
          ls -lash

          mkdir deps
          touch deps/{a,b,c}
          hash=$(find deps -type f -print0 | sort -z | xargs -0 sha1sum | sha1sum  | awk '{print $1}')
          echo "hash: $hash"
          echo "hash=$hash" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: deps
          key: deps-${{ hashFiles('*') }}
          restore-keys: |
            deps-${{ steps.deps.outputs.hash }}

  build:
    name: "Boolean is ${{ inputs.boolean }} or ${{ github.event.inputs.boolean  }}"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: "Inputs: ${{ inputs.boolean }} or ${{ github.event.inputs.boolean  }}"

        run: |
          echo "environment is ${{ github.event.inputs.environment }} / ${{ inputs.environment }}"
          echo "boolean is ${{ github.event.inputs.boolean }}" / ${{ inputs.boolean }}
          echo "choice is ${{ github.event.inputs.choice }}" / ${{ inputs.choice }}
