name: start-experiment
env:
  DEFAULT_WORKLOAD_COMMIT: main
  NUM_VALIDATORS: 5
  IMAGE_1: rippled:${{github.run_id}}-${{github.run_number}}-${{github.run_attempt}}
  IMAGE_2: workload:${{github.run_id}}-${{github.run_number}}-${{github.run_attempt}}
  IMAGE_3: config:${{github.run_id}}-${{github.run_number}}-${{github.run_attempt}}

on:
  push:
  workflow_dispatch:
    inputs:
      rippled_repo:
        description: 'Git rippled repo'
        default: https://github.com/XRPLF/rippled.git
        required: true
        type: string
      rippled_commit:
        description: 'Git rippled branch/commit'
        default: develop
        required: true
        type: string
      workload_commit:
        description: 'Git workload branch/commit'
        default: main
        required: true
        type: string

jobs:
  build_1:
    strategy:
      fail-fast: false
      matrix:
        manual:
          -
          - "True"
          - ''
          - 'False'
        runit:
          - "yes"
          - "no"
          - "whoknows"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build image 1
        run: |
          docker build . -f Dockerfile.1 -t image_1
      - name: use action with runit=${{ matrix.runit }}
        uses: ./.github/actions/cond
        with:
          condition: True
          runit: ${{ matrix.runit }}
          manual: ${{ matrix.manual }}

  build_2:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image 2
        run: |
          docker build . -f Dockerfile.1 -t image_2
      - name: use action
        uses: ./.github/actions/cond
        with:
          condition: False
          manual: ${{ matrix.manual }}
  build_3:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build image 3
        run: |
          docker build . -f Dockerfile.3 -t image_3

  run_all:
    runs-on: ubuntu-latest
    needs: [build_1, build_2, build_3]
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Run them all
        run: |
          docker run image_1
          docker run image_2
          docker run image_3
