name: "Label Previous Pull Requests"
on:
  push:
  pull_request:
  pull_request_target:

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Label PRs 1, 2, and 3
    - uses: actions/labeler@v5
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        pr-number: |
          1
