name: nix
on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dependencies:
    name: Linux deps ${{ matrix.compiler }}-${{ matrix.compiler_version }} ${{ matrix.configuration }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux
        compiler:
          - gcc
        configuration:
          - Release
        include:
          - compiler: gcc
            compiler_version: 11
    runs-on: [ubuntu-latest]
    container: ghcr.io/xrplf/rippled-build-ubuntu:aaf5e3e
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Configure Conan
        uses: ./.github/actions/build
