name: Main workflow

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened

jobs:
  call-workflow-passing-data:
    strategy:
      matrix:
        the_os:
          - Linux
          - macOS
          - Windows

    uses: ./.github/workflows/base_workflow.yml
    with:
      config-path: .github/labeler.yml
      os: ${{ matrix.the_os }}
    secrets: inherit
      # personal_access_token: ${{ secrets.token }}

  # wf_trigger_test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #     - name: Do the thing
  #       run: |
  #           echo "Am running"
