name: Main workflow

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
  pull_request_target:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - Linux
          - macOS
          - Windows
        include:
          - os: Windows
            more_values: "true"
          - os: Linux
            compiler: [ {cpp: g++, c: gcc}, {cpp: g++-8, c: gcc-8}, {cpp: clang++, c: clang} ]
          - os: macOS
            cmake_flags:
              - cmake_flags: "-Dmacos=ON"
    uses: ./.github/workflows/base_workflow.yml
    with:
      config-path: .github/labeler.yml
      os: ${{ matrix.os }}
    secrets: inherit

  # wf_trigger_test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #     - name: Do the thing
  #       run: |
  #           echo "Am running"
